# Site
name: "Senso Crítico"
title: "Senso Crítico"
description: "Portal de notícias"
email: 
logo: 'assets/images/logo-226-64.png'
favicon: 'assets/images/favicon-32.png' 
baseurl: ""
google_analytics: 'UA-167317800-1'
disqus: 'sensocritico'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:categories/:year/:month/:day/:title

# Authors
authors:
  felipe:
    name: Felipe
    display_name: Felipe Mota    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: felipemotacontato@gmail.com
    twitter: https://twitter.com/felipemotabr
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  flavia:
    name: Flavia
    display_name: Flavia Moura
    avatar: 'assets/images/avatar.png'
    email: 
    twitter: 
    description: ""
  redacao:
    name: Redação
    display_name: Redação
    avatar: 'assets/images/avatar.png'
    email: redacao@sensocriticoonline.com.br
    twitter: 
    description: ""


# Social Profiles
instagram_username: sensocriticoonline
twitter_username:   
facebook_username: sensocriticoonline

collections:
  category:
    output: true
    permalink: :slug/

    


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
